Numpy


Faster than lists(upto 50 times) and takes lesser space

In [1]:
# importing numpy
import numpy as np

In [2]:
#Creating Numpy array from a python list
a=[1,2,3,4,5,]
arr=np.array(a)
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
# Creating Numpy arrasy from tuples
t=(1,2,3,4,5,)
tup_arr=np.array(t)
tup_arr

array([1, 2, 3, 4, 5])

In [11]:
#Dimensions in array
arr1=np.array((45,56))

In [12]:
arr1

array([45, 56])

In [16]:
arr1.ndim

1

2-D array: Array having 1-D arrays as its elements.

In [17]:
arr = np.array([[1,2,3],[4,5,6]])

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr.ndim

2

In [21]:
mat  = np.mat(np.array([[1,2,3],[4,5,6]]))
mat

matrix([[1, 2, 3],
        [4, 5, 6]])

3- D array : 2-D arrays behave as element

In [26]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[3,4,5]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [3, 4, 5]]])

In [27]:
arr.ndim

3

Higher Dimesnional Arrays

In [31]:
arr = np.array([1,2,3], ndmin = 5)
arr


array([[[[[1, 2, 3]]]]])

In [32]:
arr.ndim

5